# Use the official Python 3.9 image as a base
FROM python:3.9

# Set the working directory
WORKDIR /code

# Copy the requirements file
COPY ./requirements.txt /code/requirements.txt

# Install the required packages
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Install FFmpeg
RUN apt-get -y update
RUN apt-get -y install ffmpeg

# Create a non-root user
RUN useradd -m -u 1000 user

# Switch to the non-root user
USER user

# Set environment variables for the non-root user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

# Set the working directory for the application
WORKDIR $HOME/app

# Copy the application files with the correct ownership
COPY --chown=user . $HOME/app

# Start the Gradio application
CMD ["python", "app.py"]